apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dc7g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dc7g
    app.kubernetes.io/part-of: tkrw-pr714-0075-0043-app
  name: devfile-sample-dc7g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dc7g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dc7g
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0043-tenant/tkrw-pr714-0075-0043-app/devfile-sample-dc7g@sha256:00a8a8af5cee09ce732c11534410d0c8d5d0d99a5d3f10df54f3f570212fa31e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
